export { truths, dares, welcomeMessages };

const truths = [
  // Versi 1.0
  "Apa hal paling memalukan yang pernah kamu alami?",
  "Apa satu rahasia besar yang belum pernah kamu ceritakan kepada siapa pun?",
  "Jika kamu bisa bertukar tempat dengan seseorang selama sehari, siapa yang akan kamu pilih dan mengapa?",
  "Apa hal paling aneh yang pernah kamu makan?",
  "Apa satu hal di dalam daftar impianmu yang ingin kamu capai dalam lima tahun ke depan?",
  "Apa yang menjadi ketakutan terbesarmu yang belum pernah kamu ceritakan kepada orang lain?",
  "Ceritakan pengalaman pertamamu tentang jatuh cinta.",
  "Jika kamu memiliki kesempatan untuk melakukan perjalanan ke masa lalu, apa yang akan kamu ubah?",
  "Apa hal paling bodoh yang pernah kamu lakukan, tetapi kamu tidak pernah menyesalinya?",
  "Bagikan kisah lucu atau aneh tentang hewan peliharaanmu, jika ada.",
  "Apa hal paling menyenangkan yang pernah kamu lakukan bersama teman-temanmu?",
  "Jika kamu harus memilih satu makanan untuk dimakan setiap hari selama sebulan, makanan apa yang akan kamu pilih?",
  "Ceritakan tentang mimpi paling aneh yang pernah kamu alami.",
  "Apa satu hal yang ingin kamu pelajari atau kuasai, tetapi belum sempat kamu lakukan?",
  "Jika kamu bisa bertukar kehidupan dengan selebriti manapun, siapa yang akan kamu pilih?",
  "Bagikan momen di mana kamu berhasil mengatasi ketakutanmu.",
  "Jika kamu memiliki waktu sehari sebagai hewan, hewan apa yang kamu pilih dan mengapa?",
  "Ceritakan tentang kali pertama kamu melakukan sesuatu yang membuatmu merasa dewasa.",
  "Apa hal paling ekstrem yang ingin kamu coba dalam hidupmu?",
  "Bagikan pengalaman lucu atau aneh di sekolah atau tempat kerja.",
  // Versi 1.1
  "Apa kenangan paling mengharukan yang pernah kamu alami?",
  "Apa satu pelajaran hidup terbesar yang pernah kamu dapatkan dari pengalamanmu?",
  "Jika kamu bisa berbicara dengan siapa pun yang sudah meninggal, siapa yang akan kamu pilih dan mengapa?",
  "Apa satu kebiasaan rahasia yang ingin kamu ubah pada dirimu sendiri?",
  "Ceritakan tentang satu momen di mana kamu merasa benar-benar terhubung dengan alam.",
  "Apa impian terbesarmu yang selalu kamu simpan sendiri?",
  "Jika kamu bisa menjelajahi satu planet di tata surya selain Bumi, planet apa yang ingin kamu kunjungi?",
  "Ceritakan tentang satu kali ketika instingmu benar-benar memimpinmu ke keputusan yang tepat.",
  "Apa satu keterampilan yang ingin kamu kuasai dalam hidup, dan mengapa hal itu penting bagimu?",
  "Jika kamu bisa mengundang tiga tokoh terkenal untuk makan malam, siapa yang akan kamu undang?",
  "Ceritakan tentang satu saat di mana kamu hampir menyerah, tetapi kamu akhirnya berhasil melalui itu.",
  "Apa pengalaman terberat yang pernah kamu alami, dan bagaimana kamu bisa bertahan darinya?",
  "Jika kamu memiliki kekuatan super, apa kekuatan yang ingin kamu miliki dan bagaimana kamu akan menggunakannya?",
  "Ceritakan tentang satu pertemuan kebetulan yang mengubah pandanganmu tentang hidup.",
  "Apa satu hal di dunia ini yang ingin kamu ubah jika kamu memiliki kekuatan untuk melakukannya?",
  "Jika kamu bisa berbicara dengan hewan, hewan apa yang ingin kamu ajak bicara dan apa yang ingin kamu tanyakan?",
  "Ceritakan tentang satu kegagalan besar yang akhirnya membawamu menuju kesuksesan.",
  "Apa satu tempat di dunia yang ingin kamu kunjungi sebelum kamu mati?",
  "Jika kamu bisa menguasai satu jenis seni, apakah itu, dan mengapa itu menarik bagimu?",
  "Ceritakan tentang satu pengalaman di mana kamu merasa benar-benar hidup dan hadir dalam momen itu.",
  "Apa satu hal yang ingin kamu katakan kepada dirimu sendiri sepuluh tahun yang lalu?",
  "Jika kamu bisa menjadi karakter fiksi apa pun untuk sehari, siapa yang akan kamu pilih?",
  "Ceritakan tentang satu pengalaman yang mengajarkanmu tentang pentingnya kesabaran.",
  "Apa satu perubahan kecil dalam rutinitas harianmu yang memiliki dampak besar pada kesejahteraanmu?",
  "Jika kamu bisa bertukar tempat dengan temanmu selama sehari, apa yang ingin kamu pelajari dari perspektifnya?",
  "Ceritakan tentang satu kali ketika kamu merasa benar-benar bangga akan pencapaianmu.",
  "Apa satu masalah global yang paling ingin kamu bantu selesaikan, dan bagaimana caranya?",
  "Jika kamu bisa memahami satu bahasa baru secara instan, bahasa apa yang akan kamu pilih dan mengapa?",
  "Ceritakan tentang satu momen di mana kamu merasa terinspirasi untuk membantu orang lain.",
  "Apa satu hobi atau aktivitas yang ingin kamu coba, tetapi belum pernah kamu lakukan?",
  "Jika kamu memiliki akses ke arsip masa lalu, apa satu peristiwa bersejarah yang ingin kamu saksikan secara langsung?",
  "Ceritakan tentang satu kali ketika kamu menghadapi konflik dan memilih jalur kedamaian.",
  "Apa satu pelajaran penting yang ingin kamu ajarkan kepada generasi mendatang?",
  "Jika kamu bisa mempercepat waktu untuk satu momen dalam hidupmu, momen apa yang ingin kamu alami lebih lama?",
  "Ceritakan tentang satu kegagalan yang mengajarkanmu tentang penerimaan diri.",
  "Apa satu perjalanan impian yang ingin kamu lakukan jika uang bukanlah masalah?",
  "Jika kamu bisa mengubah satu hal tentang pendidikan di dunia, apa yang akan kamu ubah?",
  "Ceritakan tentang satu pengalaman di alam liar yang membantumu merasa terhubung dengan alam.",
  "Apa satu nasihat yang pernah kamu terima dan ternyata memiliki dampak besar pada kehidupanmu?",
  "Jika kamu bisa memiliki keahlian yang instan, apakah itu, dan bagaimana kamu akan menggunakannya?",
  "Ceritakan tentang satu momen di mana kamu merasa keterampilan sosialmu benar-benar berkembang.",
  "Apa satu hal yang ingin kamu capai dalam hidup, tetapi kamu belum memiliki kesempatan untuk melakukannya?",
  "Jika kamu bisa mengubah satu kebijakan pemerintah, kebijakan apa yang ingin kamu ubah?",
  "Ceritakan tentang satu situasi di mana kamu harus menghadapi ketakutan terbesarmu.",
  "Apa satu teknologi yang belum ada sekarang, tetapi kamu harapkan akan ada di masa depan?",
  "Jika kamu bisa belajar dari satu tokoh sejarah, siapa yang akan kamu pilih dan apa yang ingin kamu pelajari?",
  "Ceritakan tentang satu kali ketika kamu merasa terinspirasi untuk membuat perubahan dalam hidupmu.",
  "Apa satu tantangan besar yang ingin kamu ambil dalam hidup, dan mengapa tantangan itu penting bagimu?",
  "Jika kamu memiliki kesempatan untuk tinggal di tempat lain selama setahun, di mana tempat itu dan mengapa?",
  "Ceritakan tentang satu momen di mana kamu merasa bersyukur atas hal-hal sederhana dalam hidupmu.",
];

const dares = [
  // Versi 1.0
  "Kirim pesan kepada seseorang yang kamu kenal tetapi tidak pernah bicara sebelumnya, dan katakan bahwa kamu ingin berteman dengannya.",
  "Nyanyikan lagu favoritmu dengan semangat di depan teman-temanmu atau keluargamu.",
  "Kirim pesan ke seseorang dan bilang bahwa kamu 'kehilangan gajah peliharaan' dan tanyakan apakah mereka melihatnya.",
  "Ajak seseorang untuk berdansa, bahkan jika itu hanya tarian lucu di tempat yang ramai.",
  "Pergi ke luar dan berbicara dengan tanaman selama satu menit penuh.",
  "Kirim pesan teks kepada temanmu dengan hanya menggunakan emoji, biarkan mereka menebak apa yang kamu coba sampaikan.",
  "Buat sketsa cepat dari wajah salah satu temanmu dalam waktu 1 menit dan kirimkan padanya.",
  "Ambil selfie dengan ekspresi wajah paling aneh yang kamu bisa, lalu kirimkan ke seseorang.",
  "Kirim pesan pada seseorang dan mintalah rekomendasi buku favorit, padahal kamu tidak berniat membacanya.",
  "Beralih ke bahasa lain dalam percakapan dengan temanmu selama 5 menit.",
  "Gunakan kaus kaki di tanganmu selama 10 menit.",
  "Kirim pesan suara dengan menirukan suara hewan tertentu kepada salah satu temanmu.",
  "Pergilah ke luar dan berjalan-jalan dengan berjalan seperti penguin selama 2 menit.",
  "Kirim pesan kepada seseorang dengan menggunakan balasan hanya dalam bentuk GIF selama 5 percakapan berikutnya.",
  "Ajak seseorang untuk bermain tebak-tebakan lucu denganmu di media sosial.",
  "Gunakan topi atau aksesori lucu di kepalamu saat makan malam atau pertemuan keluarga.",
  "Pilih satu temanmu dan ceritakan lelucon konyol setiap jam selama 3 jam.",
  "Buatlah seni dengan menggunakan makanan dan kirimkan gambarnya kepada seseorang.",
  "Ambil selfie dengan ekspresi wajah paling seram yang kamu bisa, lalu kirimkan ke seseorang.",
  "Kirim pesan pada seseorang dengan menggunakan huruf besar semua selama 10 percakapan berikutnya.",
  // Versi 1.1
  
];

const welcomeMessages = [
  "Selamat datang di Truth or Dare buatan Serenity! Klik tombol 'Truth' atau 'Dare' untuk mendapatkan pertanyaan atau tantangan yang menarik. Bersiaplah untuk menjalani momen seru bersama teman-teman!",
  "Peraturan permainan: Pilih salah satu tombol 'Truth' atau 'Dare' untuk mendapatkan pertanyaan atau tantangan. Jangan lupa untuk bermain dengan jujur dan menghormati batasan teman-temanmu!",
  "Waktunya bersenang-senang! Pilihlah dengan berani dan nikmati setiap momen seru dalam permainan Truth or Dare ini. Jangan ragu untuk tertawa dan merasakan pengalaman yang tak terlupakan!",
  "Mari mulai dengan memilih 'Truth' atau 'Dare'. Ingatlah, tidak ada jawaban atau tindakan yang salah di sini. Jadilah dirimu sendiri dan biarkan momen kocak menghiasi permainan ini!",
];
