/* =========================
   TRUTH OR DARE DATA
========================= */

export const TOD_DATA = {
  basic: {
    truths: [
      "Apa hal paling memalukan yang pernah kamu alami?",
      "Apa satu rahasia besar yang belum pernah kamu ceritakan kepada siapa pun?",
      "Jika kamu bisa bertukar tempat dengan seseorang selama sehari, siapa dia?",
      "Apa ketakutan terbesarmu?",
      "Ceritakan pengalaman pertamamu jatuh cinta.",
      "Hal apa yang paling sering kamu pikirkan sebelum tidur?",
      "Siapa orang terakhir yang kamu chat hari ini?",
      "Apa kebiasaan kecilmu yang jarang diketahui orang lain?",
      "Hal apa yang paling kamu syukuri saat ini?",
      "Pernah bohong ke orang tua? Tentang apa?",
      "Apa hal paling random yang membuatmu bahagia?",
      "Jika bisa mengulang satu momen hidup, momen apa itu?",
      "Apa mimpi teraneh yang pernah kamu alami?",
      "Hal apa yang paling membuatmu gugup?",
      "Siapa orang yang paling berpengaruh dalam hidupmu?",
      "Apa hal sederhana yang sering kamu tunda-tunda?",
      "Jika kamu punya kekuatan super, apa itu?",
      "Apa makanan yang paling tidak kamu sukai?",
      "Hal apa yang membuatmu langsung bad mood?",
      "Apa pencapaian kecil yang pernah kamu banggakan?",
      "Siapa teman yang paling sering membuatmu tertawa?",
      "Apa hal yang ingin kamu pelajari tapi belum kesampaian?",
      "Jika hari ini adalah hari bebas total, kamu akan ngapain?",
      "Apa kenangan masa kecil yang paling kamu ingat?",
      "Hal apa yang ingin kamu perbaiki dari dirimu?",
    ],
    dares: [
      "Nyanyikan lagu favoritmu selama 30 detik.",
      "Ambil selfie dengan ekspresi paling aneh.",
      "Kirim emoji acak ke salah satu kontakmu.",
      "Berdiri dan lakukan 10 jumping jack.",
      "Ucapkan kata 'Aku berani' dengan suara lantang.",
      "Tepuk tangan selama 15 detik tanpa berhenti.",
      "Senyum lebar tanpa bicara selama 20 detik.",
      "Sebutkan 3 hal yang kamu sukai dari dirimu sendiri.",
      "Lakukan pose paling percaya diri selama 10 detik.",
      "Ucapkan alfabet terbalik secepat mungkin.",
      "Tirukan suara hewan pilihanmu.",
      "Bilang 'Aku siap tantangan!' dengan gaya dramatis.",
      "Berdiri dan putar badan 3 kali.",
      "Kedipkan mata cepat selama 10 detik.",
      "Ceritakan hal lucu yang pernah kamu alami.",
      "Buat ekspresi kaget lalu tahan 5 detik.",
      "Hitung mundur dari 10 dengan suara keras.",
      "Ucapkan nama lengkapmu dengan intonasi lucu.",
      "Lakukan pose superhero pilihanmu.",
      "Tunjuk satu benda di sekitar dan puji benda itu.",
      "Lakukan peregangan tangan dan bahu.",
      "Bilang 'Aku PDI!' dengan penuh semangat.",
      "Berikan tepuk tangan untuk dirimu sendiri.",
      "Buat gerakan bebas selama 5 detik.",
      "Tarik napas dalam-dalam lalu hembuskan dengan santai.",
    ],
  },

  couple: {
    truths: [
      "Apa hal paling romantis yang pernah kamu lakukan?",
      "Apa kebiasaan pasanganmu yang paling kamu sukai?",
      "Pernah cemburu berlebihan? Kenapa?",
      "Apa kenangan terbaik bersama pasanganmu?",
      "Apa satu hal yang ingin kamu perbaiki dalam hubungan?",
      "Apa hal kecil yang dilakukan pasanganmu tapi selalu membuatmu senang?",
      "Kapan pertama kali kamu merasa benar-benar jatuh cinta padanya?",
      "Apa sifat pasanganmu yang awalnya kamu anggap biasa tapi sekarang kamu sukai?",
      "Hal apa yang paling kamu rindukan saat jauh dari pasanganmu?",
      "Apa momen sederhana bersama pasangan yang paling berkesan?",
      "Apa hal yang membuatmu merasa paling dihargai oleh pasanganmu?",
      "Jika menggambarkan hubungan kalian dengan satu kata, apa itu?",
      "Apa kebiasaan pasanganmu yang menurutmu lucu?",
      "Hal apa yang paling kamu pelajari dari hubungan ini?",
      "Apa cara favoritmu menghabiskan waktu berdua?",
      "Apa hal yang membuatmu merasa paling dekat dengan pasangan?",
      "Jika harus merencanakan kencan impian, seperti apa itu?",
      "Apa sifat pasanganmu yang ingin kamu tiru?",
      "Apa kenangan pertama kalian yang paling kamu ingat?",
      "Apa hal kecil yang sering kamu perhatikan dari pasangan?",
      "Apa momen paling menenangkan saat bersama pasangan?",
      "Apa arti cinta menurutmu saat ini?",
      "Apa hal yang ingin kamu lakukan bersama pasangan di masa depan?",
      "Apa satu hal yang membuatmu bersyukur memiliki pasanganmu?",
      "Apa perbedaan terbesar kalian yang justru kamu sukai?",
    ],
    dares: [
      "Kirim pesan romantis ke pasanganmu sekarang.",
      "Peluk pasanganmu selama 30 detik.",
      "Ucapkan satu pujian tulus ke pasanganmu.",
      "Pegang tangan pasanganmu selama 1 menit.",
      "Katakan 'terima kasih' dengan cara paling manis.",
      "Tatap mata pasanganmu selama 20 detik sambil tersenyum.",
      "Ucapkan satu hal yang kamu kagumi dari pasanganmu.",
      "Pegang tangan pasanganmu dan katakan satu hal manis.",
      "Berikan senyuman paling tulus ke pasanganmu.",
      "Ucapkan satu kenangan indah yang kamu ingat bersama pasangan.",
      "Bilang 'Aku bersyukur punya kamu' dengan suara lembut.",
      "Berikan pujian tentang kepribadian pasanganmu.",
      "Peluk pasanganmu dengan hangat selama 20 detik.",
      "Ucapkan satu harapan kecil untuk hubungan kalian.",
      "Buat janji manis sederhana ke pasanganmu.",
      "Katakan satu hal yang membuatmu merasa aman dengannya.",
      "Pegang tangan pasanganmu dan tarik napas bersama 3 kali.",
      "Katakan satu hal yang ingin kamu lakukan bersama pasangan besok.",
      "Berikan tepukan lembut di bahu pasanganmu sebagai tanda sayang.",
      "Ucapkan 'Aku bangga padamu' dengan penuh perasaan.",
      "Ceritakan satu hal yang membuatmu tersenyum hari ini ke pasanganmu.",
      "Kirim emoji hati ke pasanganmu.",
      "Bilang satu hal lucu yang kamu sukai dari pasanganmu.",
      "Dekatkan wajahmu dan tersenyum tanpa bicara selama 10 detik.",
      "Ucapkan satu kata yang menggambarkan perasaanmu saat ini.",
    ],
  },

  kids: {
    truths: [
      "Apa warna favoritmu?",
      "Siapa teman terbaikmu?",
      "Apa makanan favoritmu?",
      "Apa kartun favoritmu?",
      "Kalau jadi superhero, kekuatan apa yang kamu mau?",
      "Apa permainan favoritmu di rumah?",
      "Apa hewan yang paling kamu suka?",
      "Siapa guru favoritmu?",
      "Apa minuman favoritmu?",
      "Kalau bisa liburan, kamu mau ke mana?",
      "Apa lagu yang sering kamu nyanyikan?",
      "Apa mainan favoritmu?",
      "Apa pelajaran yang paling kamu suka?",
      "Apa buah favoritmu?",
      "Siapa tokoh kartun yang kamu suka?",
      "Apa hal paling lucu yang pernah kamu lihat?",
      "Kalau bisa terbang, mau ke mana dulu?",
      "Apa warna baju yang paling sering kamu pakai?",
      "Apa kegiatan favoritmu di sekolah?",
      "Apa cita-citamu saat besar nanti?",
      "Apa hari favoritmu dalam seminggu?",
      "Apa camilan favoritmu?",
      "Apa game atau permainan yang kamu suka?",
      "Siapa orang yang paling sering membuatmu tersenyum?",
      "Apa hal yang membuatmu senang hari ini?",
    ],
    dares: [
      "Loncat di tempat sebanyak 5 kali.",
      "Tepuk tangan 10 kali.",
      "Tirukan suara hewan favoritmu.",
      "Senyum lebar selama 10 detik.",
      "Putar badan satu kali.",
      "Lompat kecil sebanyak 3 kali.",
      "Tepuk tangan sambil tersenyum.",
      "Tirukan suara kucing atau anjing.",
      "Angkat tangan ke atas selama 5 detik.",
      "Jalan di tempat selama 10 detik.",
      "Tunjuk hidungmu dan tertawa kecil.",
      "Bilang 'Halo!' dengan suara lucu.",
      "Putar tangan seperti baling-baling.",
      "Berdiri lalu duduk pelan-pelan.",
      "Buat wajah paling lucu yang bisa kamu buat.",
      "Tepuk paha sebanyak 5 kali.",
      "Gerakkan bahu kanan dan kiri.",
      "Ucapkan satu kata lucu.",
      "Melangkah maju satu langkah.",
      "Bilang satu warna dengan suara keras.",
      "Lambaikan tangan seperti menyapa teman.",
      "Hitung sampai lima dengan suara pelan.",
      "Sentuh kepala lalu sentuh lutut.",
      "Buat suara tawa kecil.",
      "Angkat jempol sambil tersenyum.",
    ],
  },

  extreme: {
    truths: [
      "Apa rahasia paling gelap yang pernah kamu simpan?",
      "Pernah berbohong besar ke seseorang?",
      "Hal paling nekat yang pernah kamu lakukan?",
      "Apa ketakutan terdalam dalam hidupmu?",
      "Pernah menyakiti seseorang tanpa sengaja?",
      "Apa penyesalan terbesar dalam hidupmu yang masih menghantuimu sampai sekarang?",
      "Siapa orang yang paling pernah kamu kecewakan?",
      "Apa kebohongan terbesarmu yang belum pernah terbongkar?",
      "Apa hal terburuk yang pernah kamu pikirkan tentang seseorang?",
      "Pernah merasa membenci seseorang yang seharusnya kamu sayangi?",
      "Apa ketakutan terdalam yang tidak pernah kamu ceritakan ke siapa pun?",
      "Pernah merasa hidupmu tidak berarti? Kapan?",
      "Apa keputusan paling buruk yang pernah kamu buat?",
      "Siapa orang yang paling ingin kamu minta maaf, tapi belum berani?",
      "Apa rahasia tentang dirimu yang bisa mengubah cara orang memandangmu?",
      "Pernah merasa iri sampai membenci kesuksesan orang lain?",
      "Apa hal paling egois yang pernah kamu lakukan?",
      "Jika semua rahasiamu terbongkar, hal apa yang paling kamu takuti?",
      "Pernah merasa bersalah atas sesuatu yang tidak bisa kamu perbaiki?",
      "Apa bagian dari dirimu yang paling kamu benci?",
      "Pernah merasa sendirian meskipun dikelilingi banyak orang?",
      "Apa ketakutan terburuk tentang masa depanmu?",
      "Siapa orang yang paling kamu takut kehilangan?",
      "Apa luka emosional yang belum pernah sembuh?",
      "Jika hari ini adalah hari terakhirmu, hal apa yang paling kamu sesali?",
    ],
    dares: [
      "Plank selama 1 menit.",
      "Minum segelas air tanpa berhenti.",
      "Teriakkan kata 'AKU BERANI!'",
      "Push-up 15 kali.",
      "Tatap cermin selama 30 detik tanpa tertawa.",
      "Plank selama 90 detik tanpa berhenti.",
      "Push-up 20 kali (boleh berhenti sekali).",
      "Squat 30 kali sekarang juga.",
      "Tatap cermin selama 1 menit penuh tanpa berbicara.",
      "Tarik napas dalam, tahan 20 detik, lalu hembuskan perlahan.",
      "Berdiri tanpa bergerak selama 2 menit.",
      "Minum segelas air sambil berdiri dengan tangan di belakang.",
      "Ucapkan satu hal jujur tentang dirimu dengan suara lantang.",
      "Tutup mata selama 1 menit dan tetap diam.",
      "Pegang posisi wall-sit selama 60 detik.",
      "Lakukan jumping jack 40 kali.",
      "Berdiri dengan satu kaki selama 45 detik.",
      "Tulis satu ketakutanmu (atau ucapkan jika bermain offline).",
      "Push-up 10 kali dengan tempo lambat.",
      "Duduk diam tanpa melihat HP selama 3 menit.",
      "Lakukan plank sambil hitung mundur dari 30.",
      "Angkat kedua tangan ke atas selama 1 menit penuh.",
      "Ucapkan satu kalimat motivasi untuk dirimu sendiri.",
      "Tarik napas cepat 10 kali lalu diam 20 detik.",
      "Tatap lantai dan renungkan satu kesalahan hidup selama 1 menit.",
    ],
  },
};

/* =========================
   WELCOME MESSAGE
========================= */

export const welcomeMessages = [];
